# Generated by Django 5.0.4 on 2026-03-24 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nom de l'équipement"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité en stock"
                    ),
                ),
                (
                    "defective_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité défectueuse"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Discharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de départ"
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        max_length=300, verbose_name="Destination / Mission"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "En cours"), ("closed", "Clôturée")],
                        default="open",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Technicien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Décharge",
                "verbose_name_plural": "Décharges",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FieldReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        verbose_name="Rapport détaillé des actions sur le terrain"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de retour"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discharge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_report",
                        to="stock.discharge",
                        verbose_name="Décharge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport de terrain",
                "verbose_name_plural": "Rapports de terrain",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ReturnedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_returned",
                    models.PositiveIntegerField(verbose_name="Quantité ramenée"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("good", "Bon état"), ("defective", "Défectueux")],
                        default="good",
                        max_length=10,
                        verbose_name="État",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.equipment",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "field_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returned_items",
                        to="stock.fieldreport",
                        verbose_name="Rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article retourné",
                "verbose_name_plural": "Articles retournés",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "Entrée"), ("out", "Sortie")],
                        max_length=3,
                        verbose_name="Type de mouvement",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="Note"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="stock.equipment",
                        verbose_name="Équipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DischargeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(verbose_name="Quantité retirée"),
                ),
                (
                    "discharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock.discharge",
                        verbose_name="Décharge",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stock.equipment",
                        verbose_name="Équipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de décharge",
                "verbose_name_plural": "Articles de décharge",
                "unique_together": {("discharge", "equipment")},
            },
        ),
    ]
